// No packages needed. Run after editing js/*.js or locales/*.json.
const fs=require('node:fs'),path=require('node:path');
const root=__dirname;
const read=f=>fs.readFileSync(path.join(root,f),'utf8').replace(/^\uFEFF/,'');
const locales=Object.fromEntries(fs.readdirSync(path.join(root,'locales')).filter(x=>x.endsWith('.json')).map(f=>[f.slice(0,-5),JSON.parse(read('locales/'+f))]));
const data=read('js/data.js').replace(/^export /gm,'');
const app=read('js/app.js').replace(/^import .*?;\s*/,'').replace(/init\(\)\.catch\([\s\S]*?\);\s*$/,'');
const bundle=`/* Generated by build.cjs — edit the source files. */\n(()=>{\n'use strict';\nconst NUR_LOCALES=${JSON.stringify(locales)};\n${data}\n${app}\n${read('js/enhancements.js')}\ninit().catch(error=>{console.error(error);showToast('Не удалось запустить Nur. Обновите страницу.');});\n})();\n`;
fs.writeFileSync(path.join(root,'js/nur.bundle.js'),bundle);
console.log('Built js/nur.bundle.js');
